remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
google_analytics: [G-0C8JQSGZR3]
title: [Amy Lee's Tech Blogs]
description: [You've got to have some taste]
